#!/bin/bash

if [ -z "$SUBMODULES_HOME" ]; then

  echo "ERROR: SUBMODULES_HOME not available"
  exit 1
fi

SCRIPT_CLONE="$SUBMODULES_HOME/Upstreamable/clone_submodules.sh"

if ! test -e "$SCRIPT_CLONE"; then

  echo "ERROR: Script not found '$SCRIPT_CLONE'"
  exit 1
fi

bash "$SCRIPT_CLONE"
